#!/bin/bash

appname=samtools.orig

params=()

while [[ $# -gt 0 ]];
do
    params+=("$1")
    shift
done

dirname=$(dirname "`readlink -f "$0"`")

tmp="${dirname#?}"

if [ "${dirname%$tmp}" != "/" ]; then
    dirname=$PWD/$dirname
fi

LD_LIBRARY_PATH="$dirname"
export LD_LIBRARY_PATH

"$dirname/$appname" "${params[@]}"
