#!/usr/bin/env python
"""Script to upload sequencher comparison results to Google Sheets.
This script will take the Excel/TSV output files generated by the batch pipeline
and upload them directly to a Google Sheet.
"""

import argparse
import time
from pathlib import Path
from typing import Any

import gspread
import numpy as np
import pandas as pd
from loguru import logger
from oauth2client.service_account import ServiceAccountCredentials


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Upload sequencher comparison results to Google Sheets")
    parser.add_argument("-i", "--input", required=True, help="Path to the comparison file (.xlsx or .tsv)")
    parser.add_argument("-s", "--sheet_id", required=True, help="Google Sheet ID to upload data to")
    parser.add_argument("-c", "--credentials", required=True, help="Path to Google API credentials JSON file")
    parser.add_argument(
        "-w",
        "--worksheet",
        default="Comparison Results",
        help="Name of the worksheet to upload data to (default: Comparison Results)",
    )
    parser.add_argument("-r", "--replace", action="store_true", help="Replace the entire worksheet if it exists")
    parser.add_argument(
        "--no-format",
        dest="apply_format",
        action="store_false",
        help="Upload values only, leaving the worksheet's existing formatting untouched",
    )
    parser.add_argument(
        "--column-width",
        type=int,
        default=UNIFORM_COLUMN_WIDTH_PX,
        metavar="PX",
        help=f"Width applied to every column, in pixels (default: {UNIFORM_COLUMN_WIDTH_PX})",
    )
    return parser.parse_args()


def authenticate_google_sheets(credentials_file: str) -> gspread.Client | None:
    """Authenticate with Google Sheets API."""
    # Define the scope for Google Sheets
    scopes = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]

    try:
        # Setup credentials
        # oauth2client accepts list[str] scopes at runtime; type stubs are incomplete
        creds = ServiceAccountCredentials.from_json_keyfile_name(credentials_file, scopes)  # type: ignore[reportArgumentType]
        # Authorize the client
        client = gspread.authorize(creds)  # type: ignore[reportArgumentType]
        logger.success("Authentication successful!")
    except (OSError, ValueError, gspread.exceptions.APIError) as e:
        logger.error(f"Authentication failed: {e}")
        return None
    else:
        return client


def load_data(file_path: str | Path) -> pd.DataFrame | None:
    """Load data from Excel or TSV file."""
    file_ext = Path(file_path).suffix.lower()

    if file_ext not in (".xlsx", ".tsv"):
        msg = f"Unsupported file format: {file_ext}. Please provide .xlsx or .tsv file."
        raise ValueError(msg)

    try:
        df = pd.read_excel(file_path) if file_ext == ".xlsx" else pd.read_csv(file_path, sep="	")

        # Handle NaN values - replace with empty strings for JSON compatibility
        df = df.replace({np.nan: "", float("nan"): "", "nan": "", "NaN": ""})

        # Convert any numeric columns that might have inf values
        for col in df.select_dtypes(include=["float64", "float32"]).columns:
            df[col] = df[col].replace([np.inf, -np.inf], "")

        logger.info(f"Successfully loaded data from {file_path}")
    except (OSError, ValueError, pd.errors.ParserError) as e:
        logger.error(f"Error loading data: {e}")
        return None
    else:
        return df


def clean_data_for_sheets(values: list[list[Any]]) -> list[list[Any]]:
    """Clean data to ensure all values are JSON-compatible for Google Sheets API."""
    cleaned_values = []

    for row in values:
        cleaned_row = []
        for cell in row:
            # Handle NaN, inf values and convert all non-compatible values to strings
            if pd.isna(cell) or (isinstance(cell, float) and (np.isnan(cell) or np.isinf(cell))):
                cleaned_row.append("")
            elif isinstance(cell, (int, float, bool)):
                cleaned_row.append(cell)
            else:
                cleaned_row.append(str(cell))
        cleaned_values.append(cleaned_row)

    return cleaned_values


# Every column the same width, and cell text wraps, so a long value flows down
# its column instead of stretching it. Fitting each column to its content is the
# obvious alternative and was tried first, but it makes the sheet ragged: one
# column ends up six times wider than its neighbour, and the eye loses the row.
#
# 90px is about 12 characters. Narrow enough that thirteen columns come to
# 1170px and the whole table sits on one screen; a sample id or "FULL REGION"
# takes two lines at this width, which is the trade. Change it here or pass
# --column-width.
UNIFORM_COLUMN_WIDTH_PX = 90

# openpyxl PatternFill("solid", fgColor="D9EAF7") in the 0-1 form Sheets wants,
# matching how the rest of the project styles its workbooks.
HEADER_BACKGROUND = {"red": 0xD9 / 255, "green": 0xEA / 255, "blue": 0xF7 / 255}


def build_format_requests(
    sheet_id: int,
    n_cols: int,
    n_rows: int,
    column_width: int = UNIFORM_COLUMN_WIDTH_PX,
) -> list[dict[str, Any]]:
    """Requests that give every worksheet the same look.

    A worksheet the uploader creates starts with Google's defaults, while one
    that already existed keeps whatever formatting it picked up over time --
    which is why the same pipeline produced sheets that looked nothing alike.
    Applying this on every upload settles it in one direction.
    """
    header_range = {"sheetId": sheet_id, "startRowIndex": 0, "endRowIndex": 1,
                    "startColumnIndex": 0, "endColumnIndex": n_cols}
    body_range = {"sheetId": sheet_id, "startRowIndex": 1,
                  "startColumnIndex": 0, "endColumnIndex": n_cols}

    return [
        # ws.freeze_panes = "A2"
        {"updateSheetProperties": {
            "properties": {"sheetId": sheet_id, "gridProperties": {"frozenRowCount": 1}},
            "fields": "gridProperties.frozenRowCount",
        }},
        # One width for all of them, in a single request.
        {"updateDimensionProperties": {
            "range": {"sheetId": sheet_id, "dimension": "COLUMNS",
                      "startIndex": 0, "endIndex": n_cols},
            "properties": {"pixelSize": column_width},
            "fields": "pixelSize",
        }},
        # Header: bold, filled, centred both ways, wrapped.
        {"repeatCell": {
            "range": header_range,
            "cell": {"userEnteredFormat": {
                "backgroundColor": HEADER_BACKGROUND,
                "textFormat": {"bold": True},
                "wrapStrategy": "WRAP",
                "verticalAlignment": "MIDDLE",
                "horizontalAlignment": "CENTER",
            }},
            "fields": ("userEnteredFormat(backgroundColor,textFormat,wrapStrategy,"
                       "verticalAlignment,horizontalAlignment)"),
        }},
        # Body: wrapped, so a fixed-width column flows the text downwards.
        {"repeatCell": {
            "range": body_range,
            "cell": {"userEnteredFormat": {
                "wrapStrategy": "WRAP",
                "verticalAlignment": "TOP",
                "horizontalAlignment": "LEFT",
            }},
            "fields": "userEnteredFormat(wrapStrategy,verticalAlignment,horizontalAlignment)",
        }},
        # Rows keep whatever height they were last given, so a sheet formatted
        # once with a fixed height would clip the wrapped text. Hand them back.
        {"autoResizeDimensions": {
            "dimensions": {"sheetId": sheet_id, "dimension": "ROWS",
                           "startIndex": 0, "endIndex": max(n_rows, 1)},
        }},
        # ws.auto_filter.ref = ws.dimensions
        {"setBasicFilter": {"filter": {"range": header_range}}},
    ]


def apply_formatting(
    worksheet: gspread.Worksheet,
    data_df: pd.DataFrame,
    column_width: int = UNIFORM_COLUMN_WIDTH_PX,
) -> None:
    """Format the worksheet. Never let this fail the upload -- data matters more."""
    try:
        requests = build_format_requests(
            worksheet.id, data_df.shape[1], data_df.shape[0] + 1, column_width
        )
        worksheet.spreadsheet.batch_update({"requests": requests})
        logger.info(f"Applied standard formatting ({column_width}px columns)")
    except (gspread.exceptions.APIError, KeyError, ValueError) as e:
        logger.warning(f"Data uploaded but formatting failed, leaving the worksheet as is: {e}")


def upload_to_google_sheets(
    client: gspread.Client,
    sheet_id: str,
    worksheet_name: str,
    data_df: pd.DataFrame,
    *,
    replace: bool = False,
    apply_format: bool = True,
    column_width: int = UNIFORM_COLUMN_WIDTH_PX,
) -> bool | None:
    """Upload data to Google Sheets."""
    try:
        # Open the spreadsheet
        sheet = client.open_by_key(sheet_id)

        # Check if worksheet exists, create if it doesn't
        try:
            worksheet = sheet.worksheet(worksheet_name)
            if replace:
                # Clear the worksheet if replace is True
                worksheet.clear()
                logger.info(f"Cleared existing worksheet: {worksheet_name}")
            else:
                # If not replacing, create a new worksheet with a timestamp
                timestamp = time.strftime("%Y%m%d_%H%M%S")
                worksheet_name = f"{worksheet_name}_{timestamp}"
                worksheet = sheet.add_worksheet(title=worksheet_name, rows=data_df.shape[0] + 1, cols=data_df.shape[1])
                logger.info(f"Created new worksheet: {worksheet_name}")
        except gspread.exceptions.WorksheetNotFound:
            # Create worksheet if it doesn't exist
            worksheet = sheet.add_worksheet(title=worksheet_name, rows=data_df.shape[0] + 1, cols=data_df.shape[1])
            logger.info(f"Created new worksheet: {worksheet_name}")

        # Convert DataFrame to list of lists (including headers)
        raw_values = [data_df.columns.tolist(), *data_df.to_numpy().tolist()]

        # Clean the data to ensure JSON compatibility
        values = clean_data_for_sheets(raw_values)

        # Update the worksheet
        try:
            worksheet.update(values)
            logger.debug("Worksheet updated with batch operation")
        except gspread.exceptions.APIError as e:
            # If batch update fails, try cell by cell update as fallback
            logger.warning(f"Batch update failed, trying cell by cell update: {e}")
            for r_idx, row in enumerate(values):
                for c_idx, value in enumerate(row):
                    try:
                        worksheet.update_cell(r_idx + 1, c_idx + 1, value)
                    except gspread.exceptions.APIError as cell_err:
                        logger.warning(f"Could not update cell at ({r_idx + 1}, {c_idx + 1}): {cell_err}")
                        # Set to empty string if all else fails
                        worksheet.update_cell(r_idx + 1, c_idx + 1, "")

        if apply_format:
            apply_formatting(worksheet, data_df, column_width)

        logger.success(f"Successfully uploaded data to Google Sheets worksheet: {worksheet_name}")
        # Deliberately not the sheet URL: it embeds the sheet id, and this line
        # is captured into the web UI's log view and web/runs/*.log, which the
        # operator can read over the LAN. The UI already names the target sheet.
        logger.info(f"Upload finished for worksheet: {worksheet_name}")
    except (OSError, ValueError, gspread.exceptions.APIError) as e:
        logger.error(f"Error uploading to Google Sheets: {e}")
        return False
    else:
        return True


def main() -> None:
    args = parse_args()

    # Authenticate with Google Sheets
    client = authenticate_google_sheets(args.credentials)
    if not client:
        return

    # Load the data
    data_df = load_data(args.input)
    if data_df is None:
        return

    # Upload to Google Sheets
    upload_to_google_sheets(
        client, args.sheet_id, args.worksheet, data_df,
        replace=args.replace, apply_format=args.apply_format,
        column_width=args.column_width,
    )


if __name__ == "__main__":
    main()
